<?php

 /**
 * Remove blocks from regions blocks
 */
function deployer_update_7401() {
$theme='sky';
 $result = db_query("SELECT * FROM {blocks} WHERE theme = '%s'", $theme);
  $blocks = array();
  while ($bloc = db_fetch_array($result)) {
    $blocks[$bloc['module']][$bloc['delta']] = $bloc;
  }
  
  // Remove blocks that are no longer defined by the code from the database.
  foreach ($blocks as $module => $module_block) {
    // This cleanup does not apply to disabled modules, to avoid configuration
    // being lost when modules are disabled.
    if (module_exists($module)) {
      foreach ($module_block as $delta => $block) {
         $block[$module][$delta]['status'] = 0;
         $block[$module][$delta]['region'] = BLOCK_REGION_NONE;
      }
    }
  }
}

/**
 * Enable some modules/features.
 */
function deployer_update_7402() {
  //modules
    $module_list = array(
    'comment',
  );
  module_disable($module_list);
  
  $module_list = array(
    'devel_generate',
    'strongarm',
    'features_extra',
    'realistic_dummy_content',    
    'uuid_features',
    'menu_import',
  );
  module_enable($module_list);
  
  //themes
    $theme_list = array(
    'adaptivetheme',
    'adaptivetheme_admin',
    'sky',
  );
  theme_enable($theme_list);
  
  //features
  $module_list = array(
    'fa_blocks_content',
    'fa_content_types',
    'fa_menus',
    'fa_theme_sky',
  );
  module_enable($module_list);
}

